export const BANCOS = [
    { codigo: "654", nome: "Banco A.J.Renner S.A." },
    { codigo: "246", nome: "Banco ABC Brasil S.A.www.abcbrasil.com.br " },
    { codigo: "025", nome: "Banco Alfa S.A.www.bancoalfa.com.br " },
    { codigo: "641", nome: "Banco Alvorada S.A." },
    { codigo: "213", nome: "Banco Arbi S.A.www.arbi.com.br " },
    { codigo: "019", nome: "Banco Azteca do Brasil S.A." },
    { codigo: "029", nome: "Banco Banerj S.A.www.banerj.com.br " },
    { codigo: "000", nome: "Banco Bankpar S.A.www.aexp.com " },
    { codigo: "740", nome: "Banco Barclays S.A.www.barclays.com " },
    { codigo: "107", nome: "Banco BBM S.A.www.bbmbank.com.br " },
    { codigo: "031", nome: "Banco Beg S.A.www.itau.com.br " },
    { codigo: "739", nome: "Banco BGN S.A.www.bgn.com.br " },
    { codigo: "096", nome: "Banco BM & F de Serviços de Liquidação e Custódia S.A	www.bmf.com.br " },
    { codigo: "318", nome: "Banco BMG S.A.www.bancobmg.com.br " },
    { codigo: "752", nome: "Banco BNP Paribas Brasil S.A.www.bnpparibas.com.br " },
    { codigo: "248", nome: "Banco Boavista Interatlântico S.A." },
    { codigo: "218", nome: "Banco Bonsucesso S.A.www.bancobonsucesso.com.br " },
    { codigo: "065", nome: "Banco Bracce S.A.www.lemon.com " },
    { codigo: "036", nome: "Banco Bradesco BBI S.A." },
    { codigo: "204", nome: "Banco Bradesco Cartões S.A.www.iamex.com.br " },
    { codigo: "394", nome: "Banco Bradesco Financiamentos S.A.www.bmc.com.br " },
    { codigo: "237", nome: "Banco Bradesco S.A.www.bradesco.com.br " },
    { codigo: "225", nome: "Banco Brascan S.A.www.bancobrascan.com.br " },
    { codigo: "M15", nome: "Banco BRJ S.A.www.brjbank.com.br " },
    { codigo: "208", nome: "Banco BTG Pactual S.A.www.pactual.com.br " },
    { codigo: "044", nome: "Banco BVA S.A.www.bancobva.com.br " },
    { codigo: "263", nome: "Banco Cacique S.A.www.bancocacique.com.br " },
    { codigo: "473", nome: "Banco Caixa Geral - Brasil S.A." },
    { codigo: "412", nome: "Banco Capital S.A.www.bancocapital.com.br " },
    { codigo: "040", nome: "Banco Cargill S.A.www.bancocargill.com.br " },
    { codigo: "745", nome: "Banco Citibank S.A.www.citibank.com.br " },
    { codigo: "M08", nome: "Banco Citicard S.A.www.credicardbanco.com.br " },
    { codigo: "241", nome: "Banco Clássico S.A." },
    { codigo: "M19", nome: "Banco CNH Capital S.A.www.bancocnh.com.br " },
    { codigo: "215", nome: "Banco Comercial e de Investimento Sudameris S.A.www.sudameris.com.br " },
    { codigo: "756", nome: "Banco Cooperativo do Brasil S.A. - BANCOOB	www.bancoob.com.br " },
    { codigo: "748", nome: "Banco Cooperativo Sicredi S.A.www.sicredi.com.br " },
    { codigo: "075", nome: "Banco CR2 S.A.www.bancocr2.com.br " },
    { codigo: "721", nome: "Banco Credibel S.A.www.credibel.com.br " },
    { codigo: "222", nome: "Banco Credit Agricole Brasil S.A.www.calyon.com.br " },
    { codigo: "505", nome: "Banco Credit Suisse(Brasil) S.A.www.csfb.com " },
    { codigo: "229", nome: "Banco Cruzeiro do Sul S.A.www.bcsul.com.br " },
    { codigo: "266", nome: "Banco Cédula S.A.www.bancocedula.com.br " },
    { codigo: "003", nome: "Banco da Amazônia S.A.www.bancoamazonia.com.br " },
    { codigo: "083", nome: "- 3	Banco da China Brasil S.A." },
    { codigo: "M21", nome: "Banco Daimlerchrysler S.A.www.bancodaimlerchrysler.com.br " },
    { codigo: "707", nome: "Banco Daycoval S.A.www.daycoval.com.br " },
    { codigo: "300", nome: "Banco de La Nacion Argentina	www.bna.com.ar " },
    { codigo: "495", nome: "Banco de La Provincia de Buenos Aires	www.bapro.com.ar " },
    { codigo: "494", nome: "Banco de La Republica Oriental del Uruguay" },
    { codigo: "M06", nome: "Banco de Lage Landen Brasil S.A.www.delagelanden.com " },
    { codigo: "024", nome: "Banco de Pernambuco S.A. - BANDEPE	www.bandepe.com.br " },
    { codigo: "456", nome: "Banco de Tokyo-Mitsubishi UFJ Brasil S.A.www.btm.com.br " },
    { codigo: "214", nome: "Banco Dibens S.A.www.bancodibens.com.br " },
    { codigo: "001", nome: "Banco do Brasil S.A.www.bb.com.br " },
    { codigo: "047", nome: "Banco do Estado de Sergipe S.A.www.banese.com.br " },
    { codigo: "037", nome: "Banco do Estado do Pará S.A.www.banparanet.com.br " },
    { codigo: "039", nome: "Banco do Estado do Piauí S.A. - BEP	www.bep.com.br " },
    { codigo: "041", nome: "Banco do Estado do Rio Grande do Sul S.A.www.banrisul.com.br " },
    { codigo: "004", nome: "Banco do Nordeste do Brasil S.A.www.banconordeste.gov.br " },
    { codigo: "265", nome: "Banco Fator S.A.www.bancofator.com.br " },
    { codigo: "M03", nome: "Banco Fiat S.A.www.bancofiat.com.br " },
    { codigo: "224", nome: "Banco Fibra S.A.www.bancofibra.com.br " },
    { codigo: "626", nome: "Banco Ficsa S.A.www.ficsa.com.br " },
    { codigo: "M18", nome: "Banco Ford S.A.www.bancoford.com.br " },
    { codigo: "233", nome: "Banco GE Capital S.A.www.ge.com.br " },
    { codigo: "734", nome: "Banco Gerdau S.A.www.bancogerdau.com.br " },
    { codigo: "M07", nome: "Banco GMAC S.A.www.bancogm.com.br " },
    { codigo: "612", nome: "Banco Guanabara S.A.www.bcoguan.com.br " },
    { codigo: "M22", nome: "Banco Honda S.A.www.bancohonda.com.br " },
    { codigo: "063", nome: "Banco Ibi S.A.Banco Múltiplo	www.ibi.com.br " },
    { codigo: "M11", nome: "Banco IBM S.A.www.ibm.com / br / financing /" },
    { codigo: "604", nome: "Banco Industrial do Brasil S.A.www.bancoindustrial.com.br " },
    { codigo: "320", nome: "Banco Industrial e Comercial S.A.www.bicbanco.com.br " },
    { codigo: "653", nome: "Banco Indusval S.A.www.indusval.com.br " },
    { codigo: "630", nome: "Banco Intercap S.A.www.intercap.com.br " },
    { codigo: "077", nome: "- 9	Banco Intermedium S.A.www.intermedium.com.br " },
    { codigo: "249", nome: "Banco Investcred Unibanco S.A." },
    { codigo: "M09", nome: "Banco Itaucred Financiamentos S.A.www.itaucred.com.br " },
    { codigo: "184", nome: "Banco Itaú BBA S.A.www.itaubba.com.br " },
    { codigo: "479", nome: "Banco ItaúBank S.A	www.itaubank.com.br " },
    { codigo: "376", nome: "Banco J.P.Morgan S.A.www.jpmorgan.com " },
    { codigo: "074", nome: "Banco J.Safra S.A.www.jsafra.com.br " },
    { codigo: "217", nome: "Banco John Deere S.A.www.johndeere.com.br " },
    { codigo: "076", nome: "Banco KDB S.A.www.bancokdb.com.br " },
    { codigo: "757", nome: "Banco KEB do Brasil S.A.www.bancokeb.com.br " },
    { codigo: "600", nome: "Banco Luso Brasileiro S.A.www.lusobrasileiro.com.br " },
    { codigo: "212", nome: "Banco Matone S.A.www.bancomatone.com.br " },
    { codigo: "M12", nome: "Banco Maxinvest S.A.www.bancomaxinvest.com.br " },
    { codigo: "389", nome: "Banco Mercantil do Brasil S.A.www.mercantil.com.br " },
    { codigo: "746", nome: "Banco Modal S.A.www.bancomodal.com.br " },
    { codigo: "M10", nome: "Banco Moneo S.A.www.bancomoneo.com.br " },
    { codigo: "738", nome: "Banco Morada S.A.www.bancomorada.com.br " },
    { codigo: "066", nome: "Banco Morgan Stanley S.A.www.morganstanley.com.br " },
    { codigo: "243", nome: "Banco Máxima S.A.www.bancomaxima.com.br " },
    { codigo: "045", nome: "Banco Opportunity S.A.www.opportunity.com.br " },
    { codigo: "M17", nome: "Banco Ourinvest S.A.www.ourinvest.com.br " },
    { codigo: "623", nome: "Banco Panamericano S.A.www.panamericano.com.br " },
    { codigo: "611", nome: "Banco Paulista S.A.www.bancopaulista.com.br " },
    { codigo: "613", nome: "Banco Pecúnia S.A.www.bancopecunia.com.br " },
    { codigo: "094", nome: "- 2	Banco Petra S.A.www.personaltrader.com.br " },
    { codigo: "643", nome: "Banco Pine S.A.www.bancopine.com.br " },
    { codigo: "724", nome: "Banco Porto Seguro S.A." },
    { codigo: "735", nome: "Banco Pottencial S.A.www.pottencial.com.br " },
    { codigo: "638", nome: "Banco Prosper S.A.www.bancoprosper.com.br " },
    { codigo: "M24", nome: "Banco PSA Finance Brasil S.A." },
    { codigo: "747", nome: "Banco Rabobank International Brasil S.A.www.rabobank.com.br " },
    { codigo: "088", nome: "- 4	Banco Randon S.A." },
    { codigo: "356", nome: "Banco Real S.A.www.bancoreal.com.br " },
    { codigo: "633", nome: "Banco Rendimento S.A.www.rendimento.com.br " },
    { codigo: "741", nome: "Banco Ribeirão Preto S.A.www.brp.com.br " },
    { codigo: "M16", nome: "Banco Rodobens S.A.www.rodobens.com.br " },
    { codigo: "072", nome: "Banco Rural Mais S.A.www.rural.com.br " },
    { codigo: "453", nome: "Banco Rural S.A.www.rural.com.br " },
    { codigo: "422", nome: "Banco Safra S.A.www.safra.com.br " },
    { codigo: "033", nome: "Banco Santander(Brasil) S.A.www.santander.com.br " },
    { codigo: "250", nome: "Banco Schahin S.A.www.bancoschahin.com.br " },
    { codigo: "743", nome: "Banco Semear S.A.www.bancosemear.com.br " },
    { codigo: "749", nome: "Banco Simples S.A.www.bancosimples.com.br " },
    { codigo: "366", nome: "Banco Société Générale Brasil S.A.www.sgbrasil.com.br " },
    { codigo: "637", nome: "Banco Sofisa S.A.www.sofisa.com.br " },
    { codigo: "012", nome: "Banco Standard de Investimentos S.A.www.standardbank.com " },
    { codigo: "464", nome: "Banco Sumitomo Mitsui Brasileiro S.A." },
    { codigo: "082", nome: "- 5	Banco Topázio S.A.www.bancotopazio.com.br " },
    { codigo: "M20", nome: "Banco Toyota do Brasil S.A.www.bancotoyota.com.br " },
    { codigo: "M13", nome: "Banco Tricury S.A.www.tricury.com.br " },
    { codigo: "634", nome: "Banco Triângulo S.A.www.tribanco.com.br " },
    { codigo: "M14", nome: "Banco Volkswagen S.A.www.bancovw.com.br " },
    { codigo: "M23", nome: "Banco Volvo(Brasil) S.A." },
    { codigo: "655", nome: "Banco Votorantim S.A.www.bancovotorantim.com.br " },
    { codigo: "610", nome: "Banco VR S.A.www.vr.com.br " },
    { codigo: "370", nome: "Banco WestLB do Brasil S.A.www.westlb.com.br " },
    { codigo: "021", nome: "BANESTES S.A.Banco do Estado do Espírito Santo	www.banestes.com.br " },
    { codigo: "719", nome: "Banif-Banco Internacional do Funchal(Brasil)S.A.www.banif.com.br " },
    { codigo: "755", nome: "Bank of America Merrill Lynch Banco Múltiplo S.A.www.ml.com " },
    { codigo: "744", nome: "BankBoston N.A.www.bankboston.com.br " },
    { codigo: "073", nome: "BB Banco Popular do Brasil S.A.www.bancopopulardobrasil.com.br " },
    { codigo: "078", nome: "BES Investimento do Brasil S.A.- Banco de Investimento	www.besinvestimento.com.br " },
    { codigo: "069", nome: "BPN Brasil Banco Múltiplo S.A.www.bpnbrasil.com.br " },
    { codigo: "070", nome: "BRB - Banco de Brasília S.A.www.brb.com.br " },
    { codigo: "092", nome: "- 2	Brickell S.A.Crédito, financiamento e Investimento" },
    { codigo: "104", nome: "Caixa Econômica Federal	www.caixa.gov.br " },
    { codigo: "477", nome: "Citibank N.A.www.citibank.com / brasil " },
    { codigo: "081", nome: "- 7	Concórdia Banco S.A.www.concordiabanco.com " },
    { codigo: "097", nome: "- 3	Cooperativa Central de Crédito Noroeste Brasileiro Ltda.	" },
    { codigo: "085", nome: "- x	Cooperativa Central de Crédito Urbano-CECRED " },
    { codigo: "099", nome: "- x	Cooperativa Central de Economia e Credito Mutuo das Unicreds	" },
    { codigo: "090", nome: "- 2	Cooperativa Central de Economia e Crédito Mutuo das Unicreds	" },
    { codigo: "089", nome: "- 2	Cooperativa de Crédito Rural da Região de Mogiana " },
    { codigo: "087", nome: "- 6	Cooperativa Unicred Central Santa Catarina	" },
    { codigo: "098", nome: "- 1	Credicorol Cooperativa de Crédito Rural	" },
    { codigo: "487", nome: "Deutsche Bank S.A. - Banco Alemão	www.deutsche - bank.com.br " },
    { codigo: "751", nome: "Dresdner Bank Brasil S.A. - Banco Múltiplo	www.dkib.com.br " },
    { codigo: "064", nome: "Goldman Sachs do Brasil Banco Múltiplo S.A.www.goldmansachs.com " },
    { codigo: "062", nome: "Hipercard Banco Múltiplo S.A.www.hipercard.com.br " },
    { codigo: "399", nome: "HSBC Bank Brasil S.A. - Banco Múltiplo	www.hsbc.com.br " },
    { codigo: "168", nome: "HSBC Finance(Brasil) S.A. - Banco Múltiplo	" },
    { codigo: "492", nome: "ING Bank N.V.www.ing.com " },
    { codigo: "652", nome: "Itaú Unibanco Holding S.A.www.itau.com.br " },
    { codigo: "341", nome: "Itaú Unibanco S.A.www.itau.com.br " },
    { codigo: "079", nome: "JBS Banco S.A.www.bancojbs.com.br " },
    { codigo: "488", nome: "JPMorgan Chase Bank	www.jpmorganchase.com " },
    { codigo: "014", nome: "Natixis Brasil S.A.Banco Múltiplo	" },
    { codigo: "753", nome: "NBC Bank Brasil S.A. - Banco Múltiplo	www.nbcbank.com.br " },
    { codigo: "086", nome: "- 8	OBOE Crédito Financiamento e Investimento S.A.	" },
    { codigo: "254", nome: "Paraná Banco S.A.www.paranabanco.com.br " },
    { codigo: "409", nome: "UNIBANCO - União de Bancos Brasileiros S.A.www.unibanco.com.br " },
    { codigo: "230", nome: "Unicard Banco Múltiplo S.A.www.unicard.com.br " },
    { codigo: "091", nome: "- 4	Unicred Central do Rio Grande do Sul	www.unicred - rs.com.br " },
];
