export const METHODS_CONSTANTS = {
    TIPO_FAVORECIDO_HANDLE_CHANGE: 'TIPO_FAVORECIDO_HANDLE_CHANGE',
    NOME_HANDLE_CHANGE: 'NOME_HANDLE_CHANGE',
    TIPO_DOCUMENTO_HANDLE_CHANGE: 'TIPO_DOCUMENTO_HANDLE_CHANGE',
    NUMERO_DOCUMENTO_HANDLE_CHANGE: 'NUMERO_DOCUMENTO_HANDLE_CHANGE',
    BANCO_HANDLE_CHANGE: 'BANCO_HANDLE_CHANGE',
    AGENCIA_HANDLE_CHANGE: 'AGENCIA_HANDLE_CHANGE',
    CONTA_CHANGE_HANDLE_CHANGE: 'CONTA_CHANGE_HANDLE_CHANGE',
    DIGITO_HANDLE_CHANGE: 'DIGITO_HANDLE_CHANGE',
    TELEFONE_HANDLE_CHANGE: 'TELEFONE_HANDLE_CHANGE',
    EMAIL_HANDLE_CHANGE: 'EMAIL_HANDLE_CHANGE',
    SELECT_DAY_CLICKED: "SELECT_DAY_CLICKED"

}

export const TIPO_FAVORECIDO_CONSTANTS = { CONTA_INTERNA: "CONTA_INTERNA", CONTA_EXTERNA: "CONTA_EXTERNA" };
export const TIPO_DOCUMENTO_CONSTANTS = { CPF: "CPF", CNPJ: "CNPJ" };
export const DEFAULT_MASK_PATTERN = { MASK_CPF: '999.999.999-99', MASK_CNPJ: '99.999.999/9999-99' };
