export const METHODS_CONSTANTS = {
    AUTO_SUGGEST_CHANGE_HANDLE: 'autoSuggestChangeHandle',
    TYPE_HEAD_HANDLE_CHANGE: "typeHeadHandleChange",
    REACT_SELECT_HANDLE_CHANGE: "reactSelectHandleChange"


}

export const TIPO_FAVORECIDO_CONSTANTS = { CONTA_INTERNA: "CONTA_INTERNA", CONTA_EXTERNA: "CONTA_EXTERNA" };
export const TIPO_DOCUMENTO_CONSTANTS = { CPF: "CPF", CNPJ: "CNPJ" };
export const DEFAULT_MASK_PATTERN = { MASK_CPF: '999.999.999-99', MASK_CNPJ: '99.999.999/9999-99' };
