export const BANCOS = [
    { value: "654", description: "654 - Banco A.J.Renner S.A." },
    { value: "246", description: "Banco ABC Brasil S.A.www.abcbrasil.com.br " },
    { value: "025", description: "Banco Alfa S.A.www.bancoalfa.com.br " },
    { value: "641", description: "Banco Alvorada S.A." },
    { value: "213", description: "Banco Arbi S.A.www.arbi.com.br " },
    { value: "019", description: "Banco Azteca do Brasil S.A." },
    { value: "029", description: "Banco Banerj S.A.www.banerj.com.br " },
    { value: "000", description: "Banco Bankpar S.A.www.aexp.com " },
    { value: "740", description: "Banco Barclays S.A.www.barclays.com " },
    { value: "107", description: "Banco BBM S.A.www.bbmbank.com.br " },
    { value: "031", description: "Banco Beg S.A.www.itau.com.br " },
    { value: "739", description: "Banco BGN S.A.www.bgn.com.br " },
    { value: "096", description: "Banco BM & F de Serviços de Liquidação e Custódia S.A	www.bmf.com.br " },
    { value: "318", description: "Banco BMG S.A.www.bancobmg.com.br " },
    { value: "752", description: "Banco BNP Paribas Brasil S.A.www.bnpparibas.com.br " },
    { value: "248", description: "Banco Boavista Interatlântico S.A." },
    { value: "218", description: "Banco Bonsucesso S.A.www.bancobonsucesso.com.br " },
    { value: "065", description: "Banco Bracce S.A.www.lemon.com " },
    { value: "036", description: "Banco Bradesco BBI S.A." },
    { value: "204", description: "Banco Bradesco Cartões S.A.www.iamex.com.br " },
    { value: "394", description: "Banco Bradesco Financiamentos S.A.www.bmc.com.br " },
    { value: "237", description: "Banco Bradesco S.A.www.bradesco.com.br " },
    { value: "225", description: "Banco Brascan S.A.www.bancobrascan.com.br " },
    { value: "M15", description: "Banco BRJ S.A.www.brjbank.com.br " },
    { value: "208", description: "Banco BTG Pactual S.A.www.pactual.com.br " },
    { value: "044", description: "Banco BVA S.A.www.bancobva.com.br " },
    { value: "263", description: "Banco Cacique S.A.www.bancocacique.com.br " },
    { value: "473", description: "Banco Caixa Geral - Brasil S.A." },
    { value: "412", description: "Banco Capital S.A.www.bancocapital.com.br " },
    { value: "040", description: "Banco Cargill S.A.www.bancocargill.com.br " },
    { value: "745", description: "Banco Citibank S.A.www.citibank.com.br " },
    { value: "M08", description: "Banco Citicard S.A.www.credicardbanco.com.br " },
    { value: "241", description: "Banco Clássico S.A." },
    { value: "M19", description: "Banco CNH Capital S.A.www.bancocnh.com.br " },
    { value: "215", description: "Banco Comercial e de Investimento Sudameris S.A.www.sudameris.com.br " },
    { value: "756", description: "Banco Cooperativo do Brasil S.A. - BANCOOB	www.bancoob.com.br " },
    { value: "748", description: "Banco Cooperativo Sicredi S.A.www.sicredi.com.br " },
    { value: "075", description: "Banco CR2 S.A.www.bancocr2.com.br " },
    { value: "721", description: "Banco Credibel S.A.www.credibel.com.br " },
    { value: "222", description: "Banco Credit Agricole Brasil S.A.www.calyon.com.br " },
    { value: "505", description: "Banco Credit Suisse(Brasil) S.A.www.csfb.com " },
    { value: "229", description: "Banco Cruzeiro do Sul S.A.www.bcsul.com.br " },
    { value: "266", description: "Banco Cédula S.A.www.bancocedula.com.br " },
    { value: "003", description: "Banco da Amazônia S.A.www.bancoamazonia.com.br " },
    { value: "083", description: "- 3	Banco da China Brasil S.A." },
    { value: "M21", description: "Banco Daimlerchrysler S.A.www.bancodaimlerchrysler.com.br " },
    { value: "707", description: "Banco Daycoval S.A.www.daycoval.com.br " },
    { value: "300", description: "Banco de La Nacion Argentina	www.bna.com.ar " },
    { value: "495", description: "Banco de La Provincia de Buenos Aires	www.bapro.com.ar " },
    { value: "494", description: "Banco de La Republica Oriental del Uruguay" },
    { value: "M06", description: "Banco de Lage Landen Brasil S.A.www.delagelanden.com " },
    { value: "024", description: "Banco de Pernambuco S.A. - BANDEPE	www.bandepe.com.br " },
    { value: "456", description: "Banco de Tokyo-Mitsubishi UFJ Brasil S.A.www.btm.com.br " },
    { value: "214", description: "Banco Dibens S.A.www.bancodibens.com.br " },
    { value: "001", description: "Banco do Brasil S.A.www.bb.com.br " },
    { value: "047", description: "Banco do Estado de Sergipe S.A.www.banese.com.br " },
    { value: "037", description: "Banco do Estado do Pará S.A.www.banparanet.com.br " },
    { value: "039", description: "Banco do Estado do Piauí S.A. - BEP	www.bep.com.br " },
    { value: "041", description: "Banco do Estado do Rio Grande do Sul S.A.www.banrisul.com.br " },
    { value: "004", description: "Banco do Nordeste do Brasil S.A.www.banconordeste.gov.br " },
    { value: "265", description: "Banco Fator S.A.www.bancofator.com.br " },
    { value: "M03", description: "Banco Fiat S.A.www.bancofiat.com.br " },
    { value: "224", description: "Banco Fibra S.A.www.bancofibra.com.br " },
    { value: "626", description: "Banco Ficsa S.A.www.ficsa.com.br " },
    { value: "M18", description: "Banco Ford S.A.www.bancoford.com.br " },
    { value: "233", description: "Banco GE Capital S.A.www.ge.com.br " },
    { value: "734", description: "Banco Gerdau S.A.www.bancogerdau.com.br " },
    { value: "M07", description: "Banco GMAC S.A.www.bancogm.com.br " },
    { value: "612", description: "Banco Guanabara S.A.www.bcoguan.com.br " },
    { value: "M22", description: "Banco Honda S.A.www.bancohonda.com.br " },
    { value: "063", description: "Banco Ibi S.A.Banco Múltiplo	www.ibi.com.br " },
    { value: "M11", description: "Banco IBM S.A.www.ibm.com / br / financing /" },
    { value: "604", description: "Banco Industrial do Brasil S.A.www.bancoindustrial.com.br " },
    { value: "320", description: "Banco Industrial e Comercial S.A.www.bicbanco.com.br " },
    { value: "653", description: "Banco Indusval S.A.www.indusval.com.br " },
    { value: "630", description: "Banco Intercap S.A.www.intercap.com.br " },
    { value: "077", description: "- 9	Banco Intermedium S.A.www.intermedium.com.br " },
    { value: "249", description: "Banco Investcred Unibanco S.A." },
    { value: "M09", description: "Banco Itaucred Financiamentos S.A.www.itaucred.com.br " },
    { value: "184", description: "Banco Itaú BBA S.A.www.itaubba.com.br " },
    { value: "479", description: "Banco ItaúBank S.A	www.itaubank.com.br " },
    { value: "376", description: "Banco J.P.Morgan S.A.www.jpmorgan.com " },
    { value: "074", description: "Banco J.Safra S.A.www.jsafra.com.br " },
    { value: "217", description: "Banco John Deere S.A.www.johndeere.com.br " },
    { value: "076", description: "Banco KDB S.A.www.bancokdb.com.br " },
    { value: "757", description: "Banco KEB do Brasil S.A.www.bancokeb.com.br " },
    { value: "600", description: "Banco Luso Brasileiro S.A.www.lusobrasileiro.com.br " },
    { value: "212", description: "Banco Matone S.A.www.bancomatone.com.br " },
    { value: "M12", description: "Banco Maxinvest S.A.www.bancomaxinvest.com.br " },
    { value: "389", description: "Banco Mercantil do Brasil S.A.www.mercantil.com.br " },
    { value: "746", description: "Banco Modal S.A.www.bancomodal.com.br " },
    { value: "M10", description: "Banco Moneo S.A.www.bancomoneo.com.br " },
    { value: "738", description: "Banco Morada S.A.www.bancomorada.com.br " },
    { value: "066", description: "Banco Morgan Stanley S.A.www.morganstanley.com.br " },
    { value: "243", description: "Banco Máxima S.A.www.bancomaxima.com.br " },
    { value: "045", description: "Banco Opportunity S.A.www.opportunity.com.br " },
    { value: "M17", description: "Banco Ourinvest S.A.www.ourinvest.com.br " },
    { value: "623", description: "Banco Panamericano S.A.www.panamericano.com.br " },
    { value: "611", description: "Banco Paulista S.A.www.bancopaulista.com.br " },
    { value: "613", description: "Banco Pecúnia S.A.www.bancopecunia.com.br " },
    { value: "094", description: "- 2	Banco Petra S.A.www.personaltrader.com.br " },
    { value: "643", description: "Banco Pine S.A.www.bancopine.com.br " },
    { value: "724", description: "Banco Porto Seguro S.A." },
    { value: "735", description: "Banco Pottencial S.A.www.pottencial.com.br " },
    { value: "638", description: "Banco Prosper S.A.www.bancoprosper.com.br " },
    { value: "M24", description: "Banco PSA Finance Brasil S.A." },
    { value: "747", description: "Banco Rabobank International Brasil S.A.www.rabobank.com.br " },
    { value: "088", description: "- 4	Banco Randon S.A." },
    { value: "356", description: "Banco Real S.A.www.bancoreal.com.br " },
    { value: "633", description: "Banco Rendimento S.A.www.rendimento.com.br " },
    { value: "741", description: "Banco Ribeirão Preto S.A.www.brp.com.br " },
    { value: "M16", description: "Banco Rodobens S.A.www.rodobens.com.br " },
    { value: "072", description: "Banco Rural Mais S.A.www.rural.com.br " },
    { value: "453", description: "Banco Rural S.A.www.rural.com.br " },
    { value: "422", description: "Banco Safra S.A.www.safra.com.br " },
    { value: "033", description: "Banco Santander(Brasil) S.A.www.santander.com.br " },
    { value: "250", description: "Banco Schahin S.A.www.bancoschahin.com.br " },
    { value: "743", description: "Banco Semear S.A.www.bancosemear.com.br " },
    { value: "749", description: "Banco Simples S.A.www.bancosimples.com.br " },
    { value: "366", description: "Banco Société Générale Brasil S.A.www.sgbrasil.com.br " },
    { value: "637", description: "Banco Sofisa S.A.www.sofisa.com.br " },
    { value: "012", description: "Banco Standard de Investimentos S.A.www.standardbank.com " },
    { value: "464", description: "Banco Sumitomo Mitsui Brasileiro S.A." },
    { value: "082", description: "- 5	Banco Topázio S.A.www.bancotopazio.com.br " },
    { value: "M20", description: "Banco Toyota do Brasil S.A.www.bancotoyota.com.br " },
    { value: "M13", description: "Banco Tricury S.A.www.tricury.com.br " },
    { value: "634", description: "Banco Triângulo S.A.www.tribanco.com.br " },
    { value: "M14", description: "Banco Volkswagen S.A.www.bancovw.com.br " },
    { value: "M23", description: "Banco Volvo(Brasil) S.A." },
    { value: "655", description: "Banco Votorantim S.A.www.bancovotorantim.com.br " },
    { value: "610", description: "Banco VR S.A.www.vr.com.br " },
    { value: "370", description: "Banco WestLB do Brasil S.A.www.westlb.com.br " },
    { value: "021", description: "BANESTES S.A.Banco do Estado do Espírito Santo	www.banestes.com.br " },
    { value: "719", description: "Banif-Banco Internacional do Funchal(Brasil)S.A.www.banif.com.br " },
    { value: "755", description: "Bank of America Merrill Lynch Banco Múltiplo S.A.www.ml.com " },
    { value: "744", description: "BankBoston N.A.www.bankboston.com.br " },
    { value: "073", description: "BB Banco Popular do Brasil S.A.www.bancopopulardobrasil.com.br " },
    { value: "078", description: "BES Investimento do Brasil S.A.- Banco de Investimento	www.besinvestimento.com.br " },
    { value: "069", description: "BPN Brasil Banco Múltiplo S.A.www.bpnbrasil.com.br " },
    { value: "070", description: "BRB - Banco de Brasília S.A.www.brb.com.br " },
    { value: "092", description: "- 2	Brickell S.A.Crédito, financiamento e Investimento" },
    { value: "104", description: "Caixa Econômica Federal	www.caixa.gov.br " },
    { value: "477", description: "Citibank N.A.www.citibank.com / brasil " },
    { value: "081", description: "- 7	Concórdia Banco S.A.www.concordiabanco.com " },
    { value: "097", description: "- 3	Cooperativa Central de Crédito Noroeste Brasileiro Ltda.	" },
    { value: "085", description: "- x	Cooperativa Central de Crédito Urbano-CECRED " },
    { value: "099", description: "- x	Cooperativa Central de Economia e Credito Mutuo das Unicreds	" },
    { value: "090", description: "- 2	Cooperativa Central de Economia e Crédito Mutuo das Unicreds	" },
    { value: "089", description: "- 2	Cooperativa de Crédito Rural da Região de Mogiana " },
    { value: "087", description: "- 6	Cooperativa Unicred Central Santa Catarina	" },
    { value: "098", description: "- 1	Credicorol Cooperativa de Crédito Rural	" },
    { value: "487", description: "Deutsche Bank S.A. - Banco Alemão	www.deutsche - bank.com.br " },
    { value: "751", description: "Dresdner Bank Brasil S.A. - Banco Múltiplo	www.dkib.com.br " },
    { value: "064", description: "Goldman Sachs do Brasil Banco Múltiplo S.A.www.goldmansachs.com " },
    { value: "062", description: "Hipercard Banco Múltiplo S.A.www.hipercard.com.br " },
    { value: "399", description: "HSBC Bank Brasil S.A. - Banco Múltiplo	www.hsbc.com.br " },
    { value: "168", description: "HSBC Finance(Brasil) S.A. - Banco Múltiplo	" },
    { value: "492", description: "ING Bank N.V.www.ing.com " },
    { value: "652", description: "Itaú Unibanco Holding S.A.www.itau.com.br " },
    { value: "341", description: "Itaú Unibanco S.A.www.itau.com.br " },
    { value: "079", description: "JBS Banco S.A.www.bancojbs.com.br " },
    { value: "488", description: "JPMorgan Chase Bank	www.jpmorganchase.com " },
    { value: "014", description: "Natixis Brasil S.A.Banco Múltiplo	" },
    { value: "753", description: "NBC Bank Brasil S.A. - Banco Múltiplo	www.nbcbank.com.br " },
    { value: "086", description: "- 8	OBOE Crédito Financiamento e Investimento S.A.	" },
    { value: "254", description: "Paraná Banco S.A.www.paranabanco.com.br " },
    { value: "409", description: "UNIBANCO - União de Bancos Brasileiros S.A.www.unibanco.com.br " },
    { value: "230", description: "Unicard Banco Múltiplo S.A.www.unicard.com.br " },
    { value: "091", description: "- 4	Unicred Central do Rio Grande do Sul	www.unicred - rs.com.br " },
];
